FROM rust:1.50.0

# Update sources to use the Debian archive for old releases
RUN sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list && \
    sed -i 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' /etc/apt/sources.list && \
    echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid-until


# Set system environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Zurich


WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
      git \
      curl

# Avoid caching issues
ARG commit_hash
RUN echo "Cloning grcov repository at commit: ${commit_hash}"

# Clone the grcov repository
RUN git clone https://github.com/mozilla/rust-code-analysis.git /app/testbed

WORKDIR /app/testbed

# Checkout the specific commit
RUN git checkout ${commit_hash}

CMD ["cargo", "build", "--release"]






