FROM rust:1.89-slim-bullseye

# Set system environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Zurich

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    pkg-config \
    libssl-dev \
    ca-certificates \
    build-essential \
    python3 \
    python3-pip \
    wget \
    zlib1g-dev \
    mercurial \
    ninja-build \
    libclang-dev


WORKDIR /app

RUN wget https://ftp.mozilla.org/pub/mozilla.org/security/nss/releases/NSS_3_110_RTM/src/nss-3.110-with-nspr-4.36.tar.gz && \
  tar xfz nss-3.110-with-nspr-4.36.tar.gz && rm nss-3.110-with-nspr-4.36.tar.gz

RUN python3 -m pip install gyp-next
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN nss-3.110/nss/build.sh

ENV NSS_DIR=/app/nss-3.110/nss

# # Avoid caching issues
ARG commit_hash
RUN echo "Cloning neqo repository at commit: ${commit_hash}"

# # Clone the grcov repository
RUN git clone https://github.com/mozilla/neqo.git /app/testbed

# Copy the line coverage retrieval script
COPY retrieve_line_coverage.py /app/retrieve_line_coverage.py

WORKDIR /app/testbed

# Install Code Coverage Tool
RUN cargo install cargo-llvm-cov

# # Checkout the specific commit
RUN git checkout ${commit_hash}

CMD ["cargo", "build", "--release"]
