FROM rust:1.89-slim-bullseye

# Set system environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Zurich

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    python3 \
    && rm -rf /var/lib/apt/lists/*

RUN rustup component add llvm-tools-preview

# Avoid caching issues
ARG commit_hash
RUN echo "Cloning grcov repository at commit: ${commit_hash}"

# Clone the grcov repository
RUN git clone https://github.com/mozilla/rust-code-analysis.git /app/testbed

WORKDIR /app/testbed

# Install Code Coverage Tool
RUN cargo install cargo-llvm-cov \
    && rm -rf /usr/local/cargo/registry \
    && rm -rf /usr/local/cargo/git


# Checkout the specific commit
RUN git checkout ${commit_hash}

CMD ["cargo", "build", "--release"]