FROM rust:1.89-bullseye

# Set system environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Zurich


WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
git

RUN rustup component add llvm-tools

ENV RUSTFLAGS=-Cinstrument-coverage

# Avoid caching issues
ARG commit_hash
RUN echo "Cloning grcov repository at commit: ${commit_hash}"

# Clone the grcov repository
RUN git clone https://github.com/mozilla/grcov.git /app/testbed


WORKDIR /app/testbed

# Install Code Coverage Tool
RUN cargo install cargo-llvm-cov

# Checkout the specific commit
RUN git checkout ${commit_hash}

CMD ["cargo", "build", "--release"]
